/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Caos
 */
public class Suma extends javax.swing.JFrame {

    /**
     * Creates new form Suma
     */
    public Suma() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        CajaNum1 = new javax.swing.JTextField();
        CajaNum2 = new javax.swing.JTextField();
        CajaTotal = new javax.swing.JTextField();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(51, 51, 0));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Adobe Garamond Pro", 1, 14)); // NOI18N
        jLabel1.setText("Suma de dos Números");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(130, 30, 140, 16);

        jLabel2.setFont(new java.awt.Font("Adobe Garamond Pro", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ingresa el segundo Número: ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 120, 170, 18);

        jLabel3.setFont(new java.awt.Font("Adobe Garamond Pro", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ingresa el primer Número: ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 80, 160, 18);

        jButton1.setFont(new java.awt.Font("Adobe Garamond Pro Bold", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("TOTAL");
        jPanel1.add(jButton1);
        jButton1.setBounds(70, 200, 120, 37);

        CajaNum1.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        CajaNum1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(CajaNum1);
        CajaNum1.setBounds(230, 80, 80, 34);

        CajaNum2.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        CajaNum2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(CajaNum2);
        CajaNum2.setBounds(230, 120, 80, 34);

        CajaTotal.setEditable(false);
        CajaTotal.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        CajaTotal.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(CajaTotal);
        CajaTotal.setBounds(224, 210, 90, 34);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(6, 6, 388, 288);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Suma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Suma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Suma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Suma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Suma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CajaNum1;
    private javax.swing.JTextField CajaNum2;
    private javax.swing.JTextField CajaTotal;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
